services:
  auth:
    build:
      context: .
    ports:
      - "6080:80"
    volumes:
      - ../${PROFILE_DIR:-./profile}:/profile
      - ./desktop:/home/abc/Desktop
    environment:
      - PUID=1000
      - PGID=1000
